server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/user/**
          - id: user-friendship-service
            uri: lb://user-service
            predicates:
              - Path=/api/friendship/**
          - id: user-relation-service
            uri: lb://user-service
            predicates:
              - Path=/api/relation/**
          - id: user-search-service
            uri: lb://user-service
            predicates:
              - Path=/api/search/**
          - id: post-service
            uri: lb://post-service
            predicates:
              - Path=/api/post/**
          - id: post-content-service
            uri: lb://post-service
            predicates:
              - Path=/api/content/**
          - id: post-react-service
            uri: lb://post-service
            predicates:
              - Path=/api/react/**
          - id: comment-service
            uri: lb://comment-service
            predicates:
              - Path=/api/comment/**
          - id: feed-service
            uri: lb://feed-service
            predicates:
              - Path=/api/feed/**
          - id: feed-additional-service
            uri: lb://feed-service
            predicates:
              - Path=/api/additional/**


management:
  tracing:
    sampling:
      probability: 1.0




