server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/user/**
          - id: user-friendship-service
            uri: lb://user-service
            predicates:
              - Path=/api/friendship/**
          - id: post-service
            uri: lb://post-service
            predicates:
              - Path=/api/post/**


management:
  tracing:
    sampling:
      probability: 1.0




